### ISSUE TITLE
Can I submit an additional icon request?

### ISSUE THREAD

**Issue by ghost** [Delta-Icons/aegis#2]
### Issue

The original aegis-icons is no longer active. Can I submit a request to add an icon here on behalf of the original?

**Comment by GitGitro** [comment]
Hi!
what do you mean "on behalf of the original"?
I sure can do an icon request but keep in mind that the icon will have [Delta's colors](https://raw.githubusercontent.com/Delta-Icons/android/master/resources/palettes/palette.svg)
